apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-hub-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/jupyter-hub"
