apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pgdata-0-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/mlflow-pgdata-0"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pgdata-1-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/mlflow-pgdata-1"
