apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: mlflow-minimal-cluster
  namespace: mlflow
  labels:
    team: mlflow

spec:
  teamId: "mlflow"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    mlflow:  # database owner
    - superuser
    - createdb
  databases:
    mlflow: mlflow # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
